src/Entity/Director.php
<?php

namespace App\Entity;

use App\Repository\DirectorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DirectorRepository::class)]
class Director
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255)]
    private ?string $last_name = null;

    #[ORM\ManyToMany(targetEntity: Movie::class, mappedBy: 'directors')]
    private Collection $movies;

    public function __construct()
    {
        $this->movies = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getFirstName().' '.$this->getLastName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    /**
     * @return Collection<int, Movie>
     */
    public function getMovies(): Collection
    {
        return $this->movies;
    }

    public function addMovie(Movie $movie): static
    {
        if (!$this->movies->contains($movie)) {
            $this->movies->add($movie);
            $movie->addDirector($this);
        }

        return $this;
    }

    public function removeMovie(Movie $movie): static
    {
        if ($this->movies->removeElement($movie)) {
            $movie->removeDirector($this);
        }

        return $this;
    }
}

src/Entity/Movie.php
<?php

namespace App\Entity;

use App\Repository\MovieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: MovieRepository::class)]
#[Vich\Uploadable]
class Movie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $release_date = null;

    #[ORM\OneToMany(mappedBy: 'movie', targetEntity: Review::class, orphanRemoval: true)]
    private Collection $reviews;

    #[ORM\ManyToMany(targetEntity: director::class, inversedBy: 'movies')]
    private Collection $directors;

    #[ORM\ManyToMany(targetEntity: genre::class, inversedBy: 'movies')]
    private Collection $genres;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $synopsis = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $duration = null;

    #[Vich\UploadableField(mapping: 'movies', fileNameProperty: 'imageName', size: 'imageSize')]
    private ?File $imageFile = null;

    #[ORM\Column(nullable: true)]
    private ?string $imageName = null;

    #[ORM\Column(nullable: true)]
    private ?int $imageSize = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    public function __construct()
    {
        $this->reviews = new ArrayCollection();
        $this->directors = new ArrayCollection();
        $this->genres = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getName();
    }

    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getReleaseDate(): ?\DateTimeInterface
    {
        return $this->release_date;
    }

    public function setReleaseDate(?\DateTimeInterface $release_date): static
    {
        $this->release_date = $release_date;

        return $this;
    }

    /**
     * @return Collection<int, Review>
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): static
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews->add($review);
            $review->setMovie($this);
        }

        return $this;
    }

    public function removeReview(Review $review): static
    {
        if ($this->reviews->removeElement($review)) {
            // set the owning side to null (unless already changed)
            if ($review->getMovie() === $this) {
                $review->setMovie(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, director>
     */
    public function getDirectors(): Collection
    {
        return $this->directors;
    }

    public function addDirector(director $director): static
    {
        if (!$this->directors->contains($director)) {
            $this->directors->add($director);
        }

        return $this;
    }

    public function removeDirector(director $director): static
    {
        $this->directors->removeElement($director);

        return $this;
    }

    /**
     * @return Collection<int, genre>
     */
    public function getGenres(): Collection
    {
        return $this->genres;
    }

    public function addGenre(genre $genre): static
    {
        if (!$this->genres->contains($genre)) {
            $this->genres->add($genre);
        }

        return $this;
    }

    public function removeGenre(genre $genre): static
    {
        $this->genres->removeElement($genre);

        return $this;
    }

    public function getSynopsis(): ?string
    {
        return $this->synopsis;
    }

    public function setSynopsis(?string $synopsis): static
    {
        $this->synopsis = $synopsis;

        return $this;
    }

    public function getDuration(): ?\DateTimeInterface
    {
        return $this->duration;
    }

    public function setDuration(?\DateTimeInterface $duration): static
    {
        $this->duration = $duration;

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageSize(?int $imageSize): void
    {
        $this->imageSize = $imageSize;
    }

    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }
}

src/Controller/MovieController.php
<?php

namespace App\Controller;

use App\Entity\Movie;
use App\Entity\Review;
use App\Form\ReviewType;
use App\Repository\MovieRepository;
use App\Repository\ReviewRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MovieController extends AbstractController
{
    #[Route('/movie', name: 'app_movies')]
    public function index(MovieRepository $movieRepository, Request $request): Response
    {
        $genreId = $request->get('genreId');
        $movies = $movieRepository->findMovie($genreId);

        dump($movies);

        return $this->render('movie/index.html.twig', [
            'movies' => $movies,
        ]);
    }


    #[Route('/movie/{id}', name: 'app_movie_show')]
    public function show(Movie $movie, Request $request, EntityManagerInterface $entityManager, Security $security, ReviewRepository $reviewRepository): Response
    {
        $averageRate = $reviewRepository->getAverageRateByMovieId($movie->getId());

        $user = $security->getUser();

        $review = $reviewRepository->findOneBy(['movie'=> $movie, 'user' => $user]);

        if(!$review) {
            $review = new Review();
            $review->setMovie($movie);
            $review->setUser($user);
            $review->setApproved(false);
        }

        $form = $this->createForm(ReviewType::class, $review);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $entityManager->persist($review);
            $entityManager->flush();
        }
        
        return $this->render('movie/show.html.twig', [
            'movie' => $movie,
            'form' => $form,
            'user' => $user,
            'averageRate' => $averageRate,
        ]);
    }
}

templates/movie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MovieController!{% endblock %}

{% block body %}
    <div class='row text-center'>
        {% for movie in movies %}
            {% include "partials/movie/movie_block.html.twig" %}
        {% endfor %}
    </div>

{% endblock %}

templates/movie/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{movie.name}}{% endblock %}

{% block body %}
<h1>{{movie.name}}</h1>
  <div class='row'>
      <div class='col'>
        Date de sortie: 
        {% if movie.releaseDate %}
          {{movie.releaseDate.format('d/m/Y')}}
        {% else %}
          N/C
        {% endif %}
      </div>

      <div class='col'>
        Durée: 
        {% if movie.duration %}
          {{movie.duration.format('H')}}h{{movie.duration.format('i')}}
        {% else %}
          N/C
        {% endif %}
      </div>

      <div class='col'>
        {% for genre in movie.genres %}
          <a href="{{ path('app_movies', {'genreId': genre.id})}}">{{ genre.name}}</a>
        {% endfor %}
      </div>

      <div class='col'>
        {% for director in movie.directors %}
          <a href="">{{ director.firstName }} {{ director.lastName }}</a>
        {% endfor %}
      </div>
  </div>

  <div class='row'>
    <div class='col'>
      {% if averageRate %}
        Note moyenne :
        <div class="rate">
          {% for i in range(5,1, -1)%}
            <input disabled="disabled" type="radio" id="avgstar{{ i }}" name="avgrate" value="{{ i }}" {{ averageRate == i ? 'checked="checked"' : ''}}>
          {% endfor %}
        </div>
      {% endif %}

    </div>
  </div>

<div class="row flex-lg-row-reverse g-5 py-5">
      <div class="col-10 col-sm-8 col-lg-4">
        {% if movie.imageName %}
            <img src="{{ vich_uploader_asset(movie, 'imageFile') }}" class="card-img-top" alt="affiche {{ movie.name}}">
        {% else %}
            <img src="{{ asset('build/images/clap.jpg') }}" class="card-img-top" alt="affiche {{ movie.name}}">
        {% endif %}
      </div>
      <div class="col-lg-8">
  
        <p class="lead">{{movie.synopsis|raw }}</p>

      </div>
    </div>

    <div class='row'>
        <h2>Noter ce film</h2>
        {% if user %}
          {{include('partials/review/form.html.twig')}}
        {% else %}
          <p>Vous devez être connecté pour pouvoir noter ce film. Rendez-vous sur la page <a href="{{ path('app_login') }}">connexion</a></p>
        {% endif %}
    </div>

{% endblock %}